name: openlibrary_tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  openlibrary_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11-dev"]
    runs-on: ubuntu-latest
    steps:
      - if: "contains(matrix.python-version, '-dev')"
        run: sudo apt-get install -y libxml2 libxslt-dev
      - name: Checkout Open Library
        uses: actions/checkout@v3
        with:
          repository: internetarchive/openlibrary
      - name: Checkout current Infogami
        uses: actions/checkout@v3
        with:
          path: vendor/infogami
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements_test.txt
      - run: make test-py
